name: etebase_dart
description: Etebase Dart API for all platforms.
version: 0.1.0
homepage: https://etebase.com

environment:
  sdk: '>=2.14.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0

dependencies:
  dartz: 0.10.0
  argon2: ^1.0.1
  http: ^0.13.3
  js: ^0.6.3
  libsodium: ^0.2.0
  flutter_sodium: ^0.2.0
  msgpack2:
    path: '../msgpack2'
  test: ^1.18.2
